name: CI

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@master
    - name: install irssi
      run: sudo apt-get -q install irssi
    - name: clone irssi-scripts
      run: git clone -q https://github.com/bw1/scripts.irssi.org.git
    - name: Run a one-line script
      run: echo Hello, world! $PWD
    - name: Run a multi-line script
      run: |
        echo Add other actions to build,
        echo test, and deploy your project.
